@startuml
class MyGame.Game.World {
- boolean showMiniMap
- Player player
- List<Enemy> enemies
- double enemySpawnTimer
- double chargersSpawnTimer
- double bossSpawnTimer
- boolean bossIsAlive
- double chargerWaveTimer
- int currentCrystalFrame
- double crystalAnimationTimer
- int currentExplosionFrame
- double explosionAnimationTimer
- int currentBlackholeFrame
- double blackholeAnimationTimer
- int currentFinalWeaponFrame
- double finalWeaponAnimationTimer
- int currentEnteringFrame
- double enteringAnimationTimer
- boolean entering
- List<Experience> experience
- List<ActiveSkill> activeSkills
- Ultimate ultimate
- boolean ultimateActive
- List<Weapon> weaponList
- Bow bow
- Sword sword
- Aura aura
- OrbitRock orbitRock
- BoomerangWeapon boomerangWeapon
- LightningWeapon lightningWeapon
- List<Rock> rocks
- List<Boomerang> boomerangs
- List<Arrow> arrows
- List<LightningEffect> lightningEffects
- List<Projectile> projectiles
- List<Chest> chests
- List<Steak> steaks
- Item item
- List<Item> itemList
- boolean gameStop
- List<Obstacle> obstacles
- double timeSurvived
- List<DamageText> damageTexts
- double difficultyMultiplier
- double adrenalCooldown
- List<Explosion> explosions
- List<double[]> blackHoles
- double rainbowTimer
- double repulsorVisualTimer
- double gasVisualTimer
- List<double[]> glitchStrikes
- List<EnergyDrink> energyDrinks
- double energyDrinkTimer
- boolean energyDrinkActive
- double drinkShieldTimer
- double drinkSpeedTimer
- boolean drinkSpeedActive
- double drinkMagnetTimer
- double screenShakeTimer
- double screenShakeIntensity
- boolean uiNeedsUpdate
- int enteringSoundCheck
- int ultimateSoundCheck
+ void mapGenerate()
+ void update(double)
+ boolean insideObstacle(double,double)
+ void spawnEnemy(int)
+ void triggerSlash(double,double)
+ void triggerSlash()
+ void triggerCrossSlash()
+ void triggerUltimate()
+ int getWeaponLevel(WeaponType)
+ void upgradeExistWeapon(Weapon,Rarity)
+ boolean isExistWeapon(Weapon)
+ void addNewWeapon(Weapon)
+ void addItem(Item)
+ boolean hasItem(String)
+ void checkCollection(List<? extends Collectable>,double)
+ void triggerScreenShake(double,double)
+ void pauseGame()
+ void resumeGame()
+ boolean isShowMiniMap()
+ void setShowMiniMap(boolean)
+ Player getPlayer()
+ void setPlayer(Player)
+ List<Enemy> getEnemies()
+ void setEnemies(List<Enemy>)
+ double getEnemySpawnTimer()
+ void setEnemySpawnTimer(double)
+ List<Experience> getExperience()
+ void setExperience(List<Experience>)
+ List<ActiveSkill> getActiveSkills()
+ void setActiveSkills(List<ActiveSkill>)
+ List<Arrow> getArrows()
+ void setArrows(List<Arrow>)
+ Bow getBow()
+ void setBow(Bow)
+ Sword getSword()
+ void setSword(Sword)
+ Aura getAura()
+ void setAura(Aura)
+ OrbitRock getOrbitRock()
+ void setOrbitRock(OrbitRock)
+ List<Chest> getChests()
+ void setChests(List<Chest>)
+ List<Steak> getSteaks()
+ void setSteaks(List<Steak>)
+ Item getItem()
+ void setItem(Item)
+ boolean isGameStop()
+ void setGameStop(boolean)
+ double getTimeSurvived()
+ void setTimeSurvived(double)
+ double getScreenShakeTimer()
+ double getScreenShakeIntensity()
+ List<DamageText> getDamageTexts()
+ void setDamageTexts(List<DamageText>)
+ List<Rock> getRocks()
+ void setRocks(List<Rock>)
+ double getChargersSpawnTimer()
+ void setChargersSpawnTimer(double)
+ List<Boomerang> getBoomerangs()
+ void setBoomerangs(List<Boomerang>)
+ BoomerangWeapon getBoomerangWeapon()
+ void setBoomerangWeapon(BoomerangWeapon)
+ List<Weapon> getWeaponList()
+ double getBossSpawnTimer()
+ void setBossSpawnTimer(double)
+ boolean isBossIsAlive()
+ void setBossIsAlive(boolean)
+ List<Item> getItemList()
+ void setItemList(List<Item>)
+ double getDifficultyMultiplier()
+ void setDifficultyMultiplier(double)
+ List<Obstacle> getObstacles()
+ void setObstacles(List<Obstacle>)
+ LightningWeapon getLightningWeapon()
+ void setLightningWeapon(LightningWeapon)
+ List<LightningEffect> getLightningEffects()
+ void setLightningEffects(List<LightningEffect>)
+ List<double[]> getBlackHoles()
+ void setBlackHoles(List<double[]>)
+ double getRainbowTimer()
+ void setRainbowTimer(double)
+ List<Explosion> getExplosions()
+ void setExplosions(List<Explosion>)
+ double getRepulsorVisualTimer()
+ void setRepulsorVisualTimer(double)
+ double getGasVisualTimer()
+ void setGasVisualTimer(double)
+ int getCurrentFinalWeaponFrame()
+ void setCurrentFinalWeaponFrame(int)
+ double getFinalWeaponAnimationTimer()
+ void setFinalWeaponAnimationTimer(double)
+ void setGlitchStrikes(List<double[]>)
+ List<EnergyDrink> getEnergyDrinks()
+ void setEnergyDrinks(List<EnergyDrink>)
+ double getEnergyDrinkTimer()
+ void setEnergyDrinkTimer(double)
+ boolean isEnergyDrinkActive()
+ void setEnergyDrinkActive(boolean)
+ double getDrinkShieldTimer()
+ void setDrinkShieldTimer(double)
+ double getDrinkSpeedTimer()
+ void setDrinkSpeedTimer(double)
+ boolean isDrinkSpeedActive()
+ void setDrinkSpeedActive(boolean)
+ double getDrinkMagnetTimer()
+ void setDrinkMagnetTimer(double)
+ boolean isUltimateActive()
+ void setUltimateActive(boolean)
+ void setScreenShakeTimer(double)
+ double getChargerWaveTimer()
+ void setChargerWaveTimer(double)
+ double getAdrenalCooldown()
+ void setAdrenalCooldown(double)
+ void setScreenShakeIntensity(double)
+ boolean isUiNeedsUpdate()
+ void setUiNeedsUpdate(boolean)
+ List<double[]> getGlitchStrikes()
+ int getCurrentCrystalFrame()
+ void setCurrentCrystalFrame(int)
+ double getCrystalAnimationTimer()
+ void setCrystalAnimationTimer(double)
+ int getCurrentExplosionFrame()
+ void setCurrentExplosionFrame(int)
+ double getExplosionAnimationTimer()
+ void setExplosionAnimationTimer(double)
+ int getCurrentBlackholeFrame()
+ void setCurrentBlackholeFrame(int)
+ double getBlackholeAnimationTimer()
+ void setBlackholeAnimationTimer(double)
+ int getCurrentEnteringFrame()
+ void setCurrentEnteringFrame(int)
+ double getEnteringAnimationTimer()
+ void setEnteringAnimationTimer(double)
+ boolean isEntering()
+ void setEntering(boolean)
+ void setWeaponList(List<Weapon>)
+ int getEnteringSoundCheck()
+ void setEnteringSoundCheck(int)
+ int getUltimateSoundCheck()
+ List<Projectile> getProjectiles()
+ void setProjectiles(List<Projectile>)
+ Ultimate getUltimate()
+ void setUltimate(Ultimate)
+ void setUltimateSoundCheck(int)
}


class MyGame.Game.Camera {
- double posX
- double posY
- double Width
- double Height
+ void update(Player)
+ double getPosX()
+ void setPosX(double)
+ double getPosY()
+ void setPosY(double)
+ double getWidth()
+ void setWidth(double)
+ double getHeight()
+ void setHeight(double)
}


class MyGame.Game.Controller {
- boolean up
- boolean down
- boolean right
- boolean left
- int totalPressed
+ void control(Scene,World,Camera)
+ void resetInput()
+ void playerMovement(Player,World)
}


class MyGame.Game.GameAssets {
+ {static} Font FONT_12
+ {static} Font FONT_15
+ {static} Font FONT_16
+ {static} Font FONT_20
+ {static} Font FONT_24
+ {static} Font FONT_30
+ {static} Font FONT_35
+ {static} Font FONT_40
+ {static} Font FONT_50
+ {static} Font FONT_60
+ {static} Font FONT_100
+ {static} Font BOLD_14
+ {static} Font BOLD_30
+ {static} Font BOLD_35
+ {static} Font BOLD_80
+ {static} Font BOLD_100
+ Image playerMech
+ Image enemyMech
+ Image chargerMech
+ Image bossMech
+ Image tile
+ WritableImage tileNormal
+ WritableImage tileCracked
+ Image props
+ Image crystal
+ Image gem
+ Image arrowImage
+ Image boomerangImage
+ Image rockImage
+ Image lightningImage
+ Image lightningImage2
+ Image slashImage
+ Image crossSlashImage
+ Image jumpingSlashImage
+ Image swordImage
+ Image auraImage
+ Image explosionImage
+ Image blackholeImage
+ Image glitchImage
+ Image enteringImage
+ Image crackedImage
+ Image bossBarImage
+ Image[] fireFrames
- Image img(String)
- {static} Font loadFont(double,boolean)
}


class MyGame.Game.Main {
+ {static} double SCREEN_WIDTH
+ {static} double SCREEN_HEIGHT
+ GameState currentState
- VBox mainMenu
- VBox settingMenu
- BorderPane uiLayer
- Pane rouletteWindow
- VBox gambaPopup
- HBox itemBox
- StackPane holdDynamicRoulette
- VBox holdDynamicStat
- Button acceptRouletteButton
- Button refreshButton
- Button skipButton
- int freeRefresh
- int refreshCost
- Button continueGameButton
- Button returnMainMenuButton
- TranslateTransition spinningAnimation
- PauseTransition pauseTransition
- Weapon winningWeapon
- Weapon randomWeapon
- Button createCustomButton(String)
+ void refreshButtonState(Player)
- Rarity gachaRarity(Player)
- VBox generateBonusStatDatabase(Weapon)
- void rouletteDatabase(World)
+ void triggerPopupLevelUp(GameEngine)
- TranslateTransition getTranslateTransition(double,int)
+ void warmUpEngine(GraphicsContext,GameEngine)
+ {static} void main(String[])
+ void start(Stage)
}


enum MyGame.Game.GameState {
+  Menu
+  Play
+  Setting
}

class MyGame.Game.SoundManager {
+ {static} AudioClip dashingSound
+ {static} AudioClip jumpingSound
+ {static} AudioClip skill1Sound
+ {static} AudioClip skill2Sound
+ {static} AudioClip jumpingSlashSound
+ {static} MediaPlayer ultimatePlayer
+ {static} MediaPlayer enteringPlayer
+ {static} AudioClip hitSound
+ {static} AudioClip swordSound
+ {static} AudioClip arrowSound
+ {static} AudioClip fireballSound
+ {static} AudioClip shurikenSound
+ {static} AudioClip auraSound
+ {static} AudioClip lightningSound
+ {static} List<AudioClip> soundManagersLists
+ {static} List<AudioClip> getSoundManagersLists()
+ {static} void initSounds()
}


class MyGame.Game.GameLauncher {
+ {static} void main(String[])
}

class MyGame.Game.GameEngine {
- Main.GameState currentGameState
- Scene scene
- World world
- Controller controller
- Camera camera
- GraphicsContext gc
- Canvas canvas
- ImageView healthFillView
- ImageView overHealFillView
- Label healthLabel
- ImageView staminaFillView
- Label staminaLabel
- ImageView expFillView
- Label levelLabel
- VBox chestUIPopup
- Label itemName
- Label itemRarityLabel
- Label itemDescribe
- Button chestContinueButton
- Button chestSkipButton
- Label killcountlabel
- ImageView killIcon
- Label coinCountLabel
- ImageView coinIcon
- Label timeSurvivedLabel
- VBox topLeftWeaponHang
- boolean chestDelayActive
- Runnable levelUpCallBack
- boolean isLevelUpCallBack
- Runnable gameOverCallBack
- GameAssets assets
- List<PlayerTrail> playerTrails
- double trailTimer
- double currentCrystalX
- double currentCrystalY
- double currentCrystalNoZ
- double crackedPosX
- double crackedPosY
- ImagePattern pattern
- Image fireBg
- int currentFireBg
- double fireBgAnimationTimer
~ ColorAdjust black
~ ColorAdjust hitFlash
~ ColorAdjust hitPlayer
~ ColorAdjust maxColor
~ ColorAdjust rainbow
- int lastCoinCount
- int lastKillCount
- int lastsecond
- MediaPlayer bgmPlayer
- int currentSongIndex
- String[] playlist
- double currentDeltaTime
+ AnimationTimer loop
+ void start()
+ void stop()
+ void renderGame(double)
+ void updateLeftPanelUI()
- void popAnimation(Node)
+ void setGameLoop()
- void playNextSong()
- void renderList(List<? extends Renderable>,GraphicsContext,double,double,double,double,double)
+ void setWorld(World)
+ World getWorld()
+ Camera getCamera()
+ void setCurrentGameState(Main.GameState)
+ void setControl(Scene,World,Camera)
+ void setLevelUpCallBack(Runnable)
+ void setGameOverCallBack(Runnable)
+ void setLevelUpCallBack(boolean)
+ GameAssets getAssets()
+ Image getPlayerMech()
+ Image getEnemyMech()
+ Image getChargerMech()
+ Image getBossMech()
+ Image getPropsImage()
+ Image getCrystal()
+ Image getGemImage()
+ Image getArrowImage()
+ Image getBoomerangImage()
+ Image getRockImage()
+ Image getLightningImage()
+ Image getLightningImage2()
+ Image getSlashImage()
+ Image getCrossSlashImage()
+ Image getJumpingSlashImage()
+ Image getSwordImage()
+ Image getAuraImage()
+ Image getExplosionImage()
+ Image getBlackholeImage()
+ Image getGlitchImage()
+ Image getEnteringImage()
+ Image getCrackedImage()
+ List<PlayerTrail> getPlayerTrails()
+ double getTrailTimer()
+ void setTrailTimer(double)
+ double getDeltaTime()
+ Effect getHitPlayer()
+ Effect getHitFlash()
}




javafx.application.Application <|-- MyGame.Game.Main
@enduml