package MyGame.GameObject.Weapon;

public enum WeaponType {
    SWORD, BOOMERANG, BOW, ROCKS, AURA, LIGHTNING,
    REGEN, LIFESTEAL, CHOAS, COIN, EXP, STAMINA, LUCK, PROJCOUNT,
    SIZE, COOLDOWN, CRITDMG, DAMAGE, ATKSPEED, CRITRATE, OVERHEAL,
    HEALTH, MOVEMENTSPD
}
